repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: basedpyright
        entry: basedpyright --pythonversion 3.11
        language: system
        pass_filenames: false

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.13
    hooks:
      - id: vulture
        args: ["aink/", "--min-confidence", "80", "--exclude", ".venv"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: radon
        name: radon
        entry: radon
        args: ["cc", "aink/", "--min=B"]
        language: system
        pass_filenames: false

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--expand-star-imports, --remove-all-unused-imports]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat
        language: system
        types: [markdown]
        exclude: "^gh_action_watcher/logs/"
